[package]
name = "restate-sdk"
version = "0.0.1"
edition = "2021"

[features]
default = ["http"]
http = ["hyper", "http-body-util", "hyper-util", "tokio/net", "restate-sdk-shared-core/http"]

[dependencies]
# restate-sdk-derive = { version = "0.0.1", path = "derive"}
restate-sdk-shared-core = { path = "../sdk-shared-core" }

pin-project-lite = "0.2"

hyper = { version = "1.4.1", optional = true, features = ["server", "http2"] }
http-body-util = { version = "0.1", optional = true }
hyper-util = { version = "0.1", features = ["tokio", "server", "server-graceful", "http2"], optional = true }

bytes = "1.6.1"
serde = "1.0"
serde_json = "1.0"
regress = "0.10"

futures = "0.3"

tokio = { version = "1", default-features = false, features = ["sync"] }

thiserror = "1.0.63"
tracing = "0.1"

tower-service = "0.3"

[dev-dependencies]
trybuild = "1.0"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3"

[build-dependencies]
prettyplease = "0.2"
serde_json = { version = "1.0" }
syn = "2.0"
typify = { version = "0.1.0" }
jsonptr = "0.5.1"


[workspace]
members = ["derive"]
